services:
  front:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: front
    restart: always
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
      WDS_SOCKET_PORT: "3000"
      TURBOPACK: "1"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"